project:
  type: website
  render: 
    - "index.qmd"
    - "experience.qmd"
    - "priorities.qmd"
  output-dir: docs
  

website:
  # title: "Trey Gordner - Ewa Neighborhood Board"
  # image: TG_1-color_website.png
  # navbar:
  #   right:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd
  #     - platform.qmd
  sidebar: 
    title: "Trey Gordner - Ewa NB Member"
    # logo: TG_1-color_website.png
    contents: auto
    search: false
    
    # icon: https://quarto.org/docs/reference/projects/websites.html#sidebar-tools

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

# TODO add image (and social icons?) above sidebar

# website reference: https://quarto.org/docs/reference/projects/websites.html#meta-project-type-upper

# theme options: https://quarto.org/docs/output-formats/html-themes.html
# for doing custom things: https://quarto.org/docs/output-formats/html-themes-more.html