project:
  type: website
  output-dir: docs

website:
  title: "Trey Gordner for Ewa Neighborhood Board"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

# TODO add image (and social icons?) above sidebar

# theme options: https://quarto.org/docs/output-formats/html-themes.html
# for doing custom things: https://quarto.org/docs/output-formats/html-themes-more.html

# publishing with GH Pages: https://quarto.org/docs/publishing/github-pages.html
# custom domain on GH Pages: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages