project:
  type: website

website:
  title: "Trey Gordner for Ewa Neighborhood Board"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

# theme options: https://quarto.org/docs/output-formats/html-themes.html
# for doing custom things: https://quarto.org/docs/output-formats/html-themes-more.html
