---
title: "Priorities"
---
### Homelessness
The primary reason for both homelessness and brain drain is that Hawaii isn't building enough homes. When many people compete for few places to live, we are forced into a cruel [game of musical chairs](https://www.youtube.com/watch?v=EQGQU0T6NBc) where home prices, rents, and property assessments all rise until the least wealthy residents are priced out--forced either to the mainland or the street. I will work with county officials to address the housing crisis at the source, making room on our island for our keiki and our homeless neighbors. I will also petition our leaders to prioritize Haubush and other Ewa hotspots for [rehabilitation programs](https://emergencyservices.honolulu.gov/core/).

### Traffic
While I advocate for more homes and more neighbors, as a trained urban planner and [land use expert](https://www.civilbeat.org/2022/06/this-group-is-trying-to-make-sense-of-hawaiis-regulatory-landscape/), I know that continuing to pave over Ewa's prime agricultural land is not the best solution to Hawaii's housing crisis. I will advocate for dense, mixed-use development concentrated in town and along the rail line to provide the affordable housing our island needs while minimizing traffic and environmental impact.

### Jobs
Ewa needs more good jobs. Instead of forcing ourselves and our neighbors to idle on the H-1 for hours every day, we should be creating well-paying opportunities right here in our own community. As a former small business owner and researcher in economic development, I look forward to helping local businesses grow and expand, and coordinating with the Kapolei and Waipahu neighborhood boards to foster sustainable, equitable prosperity in the greater Ewa area.